ECSBucket:
  Type: AWS::S3::Bucket
  Properties:
    AccessControl: PublicRead
    BucketName: ecs-bucket-8
    CorsConfiguration:
      CorsRules:
        - AllowedMethods:
            - PUT
            - GET
            - POST
            - HEAD
          AllowedOrigins:
            - "*"
          AllowedHeaders:
            - "*"
