WebAccessSecurityGroup:
  Type: AWS::EC2::SecurityGroup
  Properties:
    VpcId: !Ref VPC
    GroupName: Web-Access
    GroupDescription: Web-Access group for Custom VPC
    Tags:
      - Key: Name
        Value: Web-Access
    SecurityGroupEgress:
      - IpProtocol: "-1"
        FromPort: 0
        ToPort: 65535
        CidrIp: 0.0.0.0/0
      - IpProtocol: "-1"
        FromPort: 0
        ToPort: 65535
        CidrIpv6: "::/0"
    SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: "22"
        ToPort: "22"
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: "22"
        ToPort: "22"
        CidrIpv6: "::/0"
