BucketPolicy:
  Type: AWS::S3::BucketPolicy
  Properties:
    Bucket: !Ref Bucket
    PolicyDocument:
      Statement:
        - Action:
            - "s3:GetObject"
          Effect: Allow
          Resource: !Join
            - ""
            - - "arn:aws:s3:::"
              - !Ref Bucket
              - /*
          Principal: "*"
